apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
  namespace: kube-system
data:
  blackbox.yml: |-
    modules:
      http_2xx:  # http 检测模块  Blockbox-Exporter 中所有的探针均是以 Module 的信息进行配置
        prober: http
        timeout: 2s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          valid_status_codes: [200,301,302] # 默认 2xx，这里定义一个返回状态码，在grafana作图时，有明示。
          method: GET
          #headers:
          #  Host: prometheus.example.com
          #  Accept-Language: en-US
          #  Origin: example.com
          preferred_ip_protocol: "ip4" # 首选IP协议
        
      http_post_2xx: # http post 监测模块
        prober: http
        timeout: 2s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          method: POST
          # post 请求headers, body 这里可以不声明
          #headers:  # 使用 json 格式
          #  Content-Type: application/json
          #body: '{"text": "hello"}'
          preferred_ip_protocol: "ip4"
      tcp_connect:  # TCP 检测模块
        prober: tcp
        timeout: 2s
      dns_tcp:  # DNS 通过TCP检测模块
        prober: dns
        dns:
          transport_protocol: "tcp"  # 默认是 udp
          preferred_ip_protocol: "ip4"  # 默认是 ip6
          query_name: "kubernetes.default.svc.cluster.local" # 利用这个域名来检查 dns 服务器
          # query_type: "A"  # 如果是 kube-dns ，一定要加入这个，因为不支持Ipv6
      icmp:
        prober: icmp
        timeout: 2s
        icmp:
          preferred_ip_protocol: "ip4"
