apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-system-prometheus-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain #回收策略
  nfs:
    path: /prometheus-devops-dispute/
    server: xxxxxxxx.cn-beijing.nas.aliyuncs.com       # ----replace------
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: kube-system
  name: kube-system-prometheus-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi