apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-redis-exporter
  labels:
    app: prometheus-redis-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-redis-exporter
  labels:
    app: prometheus-redis-exporter
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [prometheus-redis-exporter]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-redis-exporter
  labels:
    app: prometheus-redis-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-redis-exporter
subjects:
- kind: ServiceAccount
  name: prometheus-redis-exporter
---

