{
 "title": "MYSQL监控指标",
 "description": "Mysql-exporter监控",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" },
   {
    "name": "DB",
    "query": "label_values(mysql_up,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{instance=~\"$DB\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL 连接拒绝次数",
   "type": "table-old",
   "description": "每秒的次数",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_aborted_connects{instance=~\"$DB\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Innodb_log_waits 量 ",
   "type": "table-old",
   "description": "Innodb_log_waits值不等于0的话，表明 innodb log  buffer 因为空间不足而等待 ",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_log_waits{instance=~\"$DB\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slave Status",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running{instance=~\"$DB\"}",
     "legendFormat": "{{instance}} > SQL"
    },
    {
     "expr": "mysql_slave_status_slave_io_running{instance=~\"$DB\"}",
     "legendFormat": "{{instance}} > Io"
    }
   ]
  },
  {
   "title": "MySQL 连接数",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{instance=~\"$DB\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL最大连接数",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "mysql_global_variables_max_connections{instance=~\"$DB\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slave Delay",
   "type": "table-old",
   "description": "SQL_Delay",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "mysql_slave_status_sql_delay{instance=~\"$DB\"}",
     "legendFormat": "{{instance}} > SQL"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "description": "5分钟的范围进行对比",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{command=\"commit\",instance=~\"$DB\"}[5m]))by(instance)+sum(rate(mysql_global_status_commands_total{command=\"rollback\",instance=~\"$DB\"}[5m]))by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{instance=~\"$DB\"}[5m]) or irate(mysql_global_status_queries{instance=~\"$DB\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "缓冲池",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum(mysql_global_status_buffer_pool_pages) by (instance) - sum(mysql_global_status_buffer_pool_pages{state=\"free\"}) by (instance)) / sum(mysql_global_status_buffer_pool_pages) by (instance))*100",
     "legendFormat": "{{instance}} -> 缓冲池 Utilization "
    },
    {
     "expr": "rate(mysql_global_status_innodb_buffer_pool_reads[2m])",
     "legendFormat": "{{instance}} -> Disk Growth "
    }
   ]
  },
  {
   "title": "MySQL 吞吐量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_questions{instance=~\"$DB\"}[2m])",
     "legendFormat": "{{instance}} -> Read rate"
    },
    {
     "expr": "sum(rate(mysql_global_status_commands_total{command=~\"insert|update|delete\",instance=~\"$DB\"}[2m])) without (command)",
     "legendFormat": "{{instance}} -> Write rate"
    }
   ]
  },
  {
   "title": "key Buffer 命中率 ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-mysql_global_status_key_reads{instance=~\"$DB\"}/mysql_global_status_key_read_requests{instance=~\"$DB\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "InnoDB Buffer命中率 ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-mysql_global_status_innodb_buffer_pool_reads{instance=~\"$DB\"}/mysql_global_status_innodb_buffer_pool_read_requests{instance=~\"$DB\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slow_queries的增长率",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Thread Cache 命中率 ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1- mysql_global_status_threads_created{instance=~\"$DB\"}/mysql_global_status_connections{instance=~\"$DB\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query Cache命中率 ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_qcache_hits/(mysql_global_status_qcache_hits+mysql_global_status_qcache_inserts)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Binlog Cache 使用状况",
   "type": "graph",
   "description": "不为0 ，可能需要调大 binlog_cache_size大小 ",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_binlog_cache_disk_use{instance=~\"$DB\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Table Cache状态量 ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_open_tables{instance=~\"$DB\"}/mysql_global_status_opened_tables{instance=~\"$DB\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Table blocked state",
   "type": "graph",
   "description": "表阻塞程度，数值较大则有问题",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_table_locks_waited/mysql_global_status_table_locks_immediate",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tmp Table Ratio  ",
   "type": "graph",
   "description": "Disk/Memory",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_created_tmp_disk_tables{instance=~\"$DB\"}/mysql_global_status_created_tmp_tables{instance=~\"$DB\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}